# Generated by Django 4.2.28 on 2026-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('', 'No preference'), ('morning', 'Morning (8 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 5 PM)'), ('evening', 'Evening (5 PM – 7 PM)')], default='', max_length=20),
        ),
    ]
