# Generated by Django 4.2.28 on 2026-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0003_auth_and_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot_time',
            field=models.TimeField(blank=True, help_text='Booked time slot e.g. 09:00', null=True),
        ),
    ]
